apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: apr23-quarkus
  janus-idp.io/tekton: apr23-quarkus
  backstage.io/kubernetes-id: apr23-quarkus
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: apr23-quarkus
resources:
  - application-dev.yaml