apiVersion: batch/v1
kind: Job
metadata:
  name: dsp-clone-job-apr23-quarkus-gitops
spec:
  template:
    metadata:
      name: dsp-clone-job-apr23-quarkus-gitops
    spec:
      serviceAccountName: apr23-quarkus-dsp-job
      containers:
        - name: initialize-dsp
          image: quay.io/redhat-ai-dev/utils:latest
          command:
            - /bin/bash
            - -c
            - |
              NS=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
              oc wait -l statefulset=apr23-quarkus-notebook --for=condition=ready pod --timeout=300s
              oc exec  StatefulSet/apr23-quarkus-notebook -- git clone https://github.com/jdubrick-ai/apr23-quarkus
      restartPolicy: Never
